name: frontend
type: nodejs:10
size: S

dependencies:
  nodejs:
    yarn: "^1.15.0"

# Because there is no composer.json file we deactivate the build flavor.
build:
  flavor: none

hooks:
  build: |
    set -e
    yarn install
    yarn run build

web:
  commands:
    # Run a no-op process that uses no CPU resources, since this is a static site.
    start: sleep infinity
  locations:
    "/":
      root: "build"
      index:
        - "index.html"
      expires: 300s
      scripts: false
      allow: false
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
          allow: true
        ^/robots\.txt$:
          allow: true
      headers:
        Access-Control-Allow-Origin: "*"

mounts:
  "/run": "shared:files/run"

disk: 128
