version: '3.4'

services:
  web:
    build:
      context: ./web
    ports:
      - "80:80"
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d:rw,cached
    depends_on:
      - coordinator
      - rssreader
      - calendarservice
      - scaffold

  scaffold:
    build:
      context: ./scaffold
    volumes:
      - ./scaffold:/app:rw,cached

  coordinator:
    build:
      context: ./coordinator
    volumes:
      - ./coordinator:/app:rw,cached

  rssreader:
    build:
      context: ./rssreader
    volumes:
      - ./rssreader:/app:rw,cached

  calendarservice:
    build:
      context: ./calendarservice
    volumes:
      - ./calendarservice:/var/www/app:rw,cached

