name: rssreader
type: nodejs:10
size: S

web:
  commands:
    start: "npm run start"
    #in this setup you will find your application stdout and stderr in /app/run/logs
  locations:
    "/":
      passthru: true

mounts:
  "/run": "shared:files/run"
  "db":
    source: local
    source_path: db

relationships:
  elasticsearch: "rssreaderelasticsearch:elasticsearch"

disk: 256

crons:
  news:
    spec: '*/15 * * * *'
    cmd: 'cd bin; ./readFeeds.js'