name: tweets
type: nodejs:10
size: S

web:
  commands:
    start: "npm run start"
    #in this setup you will find your application stdout and stderr in /app/run/logs
  locations:
    "/":
      passthru: true

relationships:
  kafka: "kafkastreaming:kafka"

mounts:
  "/run": "shared:files/run"

disk: 128