"https://{default}/":
    type: upstream
    upstream: "scaffold:http"

"https://{default}/node":
  type: upstream
  upstream: "node:http"

"https://{default}/php":
  type: upstream
  upstream: "phpservice:http"

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

