"https://{default}/":
    type: upstream
    upstream: "scaffold:http"

"https://node.{default}/":
  type: upstream
  upstream: "node:http"

"https://php.{default}/":
  type: upstream
  upstream: "phpservice:http"

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

