"https://{default}/":
    type: upstream
    upstream: "scaffold:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"https://coordinator.{default}/":
  type: upstream
  upstream: "coordinator:http"

"https://rssreader.{default}/":
  type: upstream
  upstream: "rssreader:http"

"https://calendarservice.{default}/":
  type: upstream
  upstream: "calendarservice:http"



